version: '3.8'

services:
  smartprep:
    # Build the image using the Dockerfile in the current directory
    build: .
    # Name the container
    container_name: smartprep_app
    # Map port 3000 on the host to port 3000 in the container
    ports:
      - "3000:3000"
    # Set restart policy
    restart: unless-stopped
    # Optional: Mount environment file for secrets like API keys
    # Create a file (e.g., .env.production) with GOOGLE_GENAI_API_KEY=...
    # and uncomment the line below. Ensure the file is in .dockerignore if needed.
    env_file:
      - .env.production
    # Optional: Set environment variables directly (less secure for secrets)
    # environment:
    #   - NODE_ENV=production
    #   - PORT=3000
    #   - GOOGLE_GENAI_API_KEY=your_key_here # Example, prefer env_file for secrets
    networks:
      - smartprep_network

networks:
  smartprep_network:
    driver: bridge
